### ISSUE TITLE
Laptop based killstreaks crash theatre mode

### ISSUE THREAD

**Issue by H3X1C** [XLabsProject/iw4x-client#16] opened 2019-10-04 18:21 UTC
Steps to reproduce, replay theatre clip which includes your character calling in a laptop based killstreak such as a chopper gunner. This results in the theatre clip exiting to the main menu with the message 'Lost connection to host'. Many players have reported this issue and has been an issue for a while over multiple releases.

**Comment by RektInator** [comment] 2019-10-04 21:21
This has been an issue since aIW and simply is caused by the fact that the demo code in IW4 is "experimental". a wontfix imo

**Comment by RektInator** [comment] 2019-10-07 11:33
UPDATE: it appears that server message of type 2 (exchange of config strings) is not handled correctly when opening a laptop based killstreak. It does not parse the entire network packet correctly because of that, thus leaving random garbage in the buffer, the game then tries to read this garbage as server message.

**Comment by pvorisek25** [comment] 2020-01-31 20:42
> UPDATE: it appears that server message of type 2 (exchange of config strings) is not handled correctly when opening a laptop based killstreak. It does not parse the entire network packet correctly because of that, thus leaving random garbage in the buffer, the game then tries to read this garbage as server message.

@RektInator Are you going to fix it then? Or is it a deeper problem?

**Comment by pvorisek25** [comment] 2020-02-03 15:53
> 
> 
> > UPDATE: it appears that server message of type 2 (exchange of config strings) is not handled correctly when opening a laptop based killstreak. It does not parse the entire network packet correctly because of that, thus leaving random garbage in the buffer, the game then tries to read this garbage as server message.
> 
> @RektInator Are you going to fix it then? Or is it a deeper problem?

Never mind @RektInator. The whole theater mode is kind of buggy.

**Comment by diamante0018** [comment] 2022-12-05 19:20
Fixing this bug, from a technical standpoint, is next to impossible. I would reinstate the won't fix the label.
Several big networking functions would need to be re-implemented in the iw4x-client just to properly debug this (not even fix it!).

**Closed** 2023-01-04 17:55 UTC
Labels: bug, waiting-for-community-contribution, wontfix, game-client, size: ?
