### ISSUE TITLE
[Bug] Launching the game with Steam open causes an access violation error

### ISSUE THREAD

**Issue by JoelColby** [XLabsProject/iw4x-client#303] opened 2022-06-13 02:51 UTC
It seems like an update on Steam is causing a memory access violation on launch with a fresh install: Fatal error (0xC0000005) at 0x00474DA0.

I've now had 5 folks using Steam files they just got off Steam with the same error. I suspect that this is likely due to the recent change made to add "(2009)" to the name, but I'm not sure.

A solution to get the game running in the interim period is just to completely close Steam from the icon tray. IW4x will launch normally when Steam is not running (this was tested and has worked with all 5 people reporting this error).

I've attached a minidump from someone experiencing the error (I had to zip the file, GitHub wasn't allowing me to upload a DMP file): [iw4x-v0.7.2-57-g020201ab-20220612220831.zip](https://github.com/XLabsProject/iw4x-client/files/8887565/iw4x-v0.7.2-57-g020201ab-20220612220831.zip)

**Comment by diamante0018** [comment] 2022-06-13 07:44
Duplicate of #64

**Closed** 2022-06-13 17:59 UTC
