### ISSUE TITLE
[Bug] Cannot unbind Lean Left or Lean Right

### ISSUE THREAD

**Issue by JoelColby** [XLabsProject/iw4x-client#285] opened 2022-05-27 21:29 UTC
Perhaps related to a previous issue: #276 

The IW4x client will crash with an access violation error when attempting to unbind Lean Left or Lean Right in Options -> Controls -> Actions -> Lean Left/Lean Right

**Comment by diamante0018** [comment] 2022-05-28 10:37
The issue is fixed on develop. It will be fixed for the rest of the players in the next update.

**Closed by diamante0018** 2022-05-28 10:37 UTC
