### ISSUE TITLE
Traffic consumption

### ISSUE THREAD

**Issue by K-Faktor** [XLabsProject/iw4x-client#360] opened 2022-07-14 14:34 UTC
I do not know what this is related to, but I noticed that there is a large consumption of traffic on the IW4x servers.
There are no mods and maps on the server, the server is constantly empty
And this is not a DDOS attack.

**Comment by K-Faktor** [comment] 2022-07-14 17:43
4gb of incoming and 7gb of outgoing is already too much
![Снимок экрана 2022-07-14 224042](https://user-images.githubusercontent.com/27491186/179048286-868de445-de31-4aa8-be28-648fae8eca58.png)

**Comment by Dss0** [comment] 2022-07-14 19:11
you sure that's caused by iw4x? you could check the traffic caused by the server using wireshark, set the filter to 
`udp.port == 28960` (or whatever your server port is).

**Comment by K-Faktor** [comment] 2022-07-15 01:42
Yes, I am completely sure that this happens only with iw4x servers. There are no such problems with the cod4x server.
I think this is some kind of bug.

**Comment by Dss0** [comment] 2022-07-16 19:59
well to further analyze this bug we'd have to see what exactly the traffic your server sends contains. Please run wireshark and sniff the traffic on the server's port then upload the pcap file here.

**Comment by diamante0018** [comment] 2022-08-09 14:35
Closing: too much time has passed since additional information was requested.

Please reopen this issue once you are ready to share the information requested by dss0.

**Closed by diamante0018** 2022-08-09 14:35 UTC
Labels: needs-info
